### PR TITLE
Update deprecated selectors reported by the Deprecation Cop.

### PR DESCRIPTION
**Pull request by lucasmazza**

### CODE REVIEW

**Comment by JonMidhir** [comment]
Hi, do you have any more information on this?

**Comment by lucasmazza** [comment]
@JonMidhir Atom has a [Deprecation Cop](https://github.com/atom/deprecation-cop) plugin that shows deprecated method calls and style selectors for plugins, which is meant to help with the [transition for Atom 1.0](http://blog.atom.io/2015/01/15/announcing-the-atom-1-api.html). I simply updated the syntax theme code based on what's being reported as deprecated:

**Comment by lucasmazza** [comment]
ping @JonMidhir

**Comment by JonMidhir** [comment]
Merged, will repackage tonight.

**Comment by lucasmazza** [comment]
@JonMidhir awesome :smile: while you are at it, looks like we have another deprecation to deal with: `stylesheets` should be renamed to `styles`.

**Comment by JonMidhir** [comment]
I'm flat out atm, would you mind opening another PR and I'll include it in the repackaging of the theme?

**Comment by lucasmazza** [comment]
@JonMidhir #7 :+1:

**Pull request merged**
